name: Release

on:
  push:
    branches:
      - main

env:
  APP_CI: true
  APP_ENV: development
  NODE_VERSION: 22.15.0
  PNPM_VERSION: 10.9.0

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: 'Release'
    if: github.repository == 'pizzajsdev/pizzajs'
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
      issues: read
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 'Build project'
        run: pnpm build
      - name: 'Lint'
        run: pnpm lint
      - name: 'Check missing changesets'
        run: pnpm changeset status
      - name: 'Test'
        run: pnpm test
      - name: Create Release Pull Request or Publish to package registry
        uses: changesets/action@v1
        id: changesets
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run changeset:release
          version: pnpm run changeset:version-packages
          commit: 'chore(release): update monorepo packages versions'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this project is configured to use the Github Package Registry, to use npm you need to use a token generated in npmjs.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
